import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import UserContextProvider from "@/contexts/userContext";
import CatContextProvider from "@/contexts/CatContext";
import LessonContextProvider from "@/contexts/LessonContext";
import VocaontextProvider from "@/contexts/vocaContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserContextProvider>
        <CatContextProvider>
          <LessonContextProvider>
            <VocaontextProvider>
              <ToastContainer />
              <body className={inter.className}>{children}</body>
            </VocaontextProvider>
          </LessonContextProvider>
        </CatContextProvider>
      </UserContextProvider>
    </html>
  );
}
