import { Inter } from "next/font/google";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/modules/dashboard/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ToastContainer />
      <body className={inter.className}>
        <div className="h-[100vh] flex  w-[100%] ]">
          <Sidebar />
          <div className="ml-[256px] h-full w-full ">
            <div className="p-[40px]">
              <Header />
              {children}
            </div>
            {/* <Footer /> */}
          </div>
        </div>
      </body>
    </html>
  );
}
